before:
  hooks:
    - go mod tidy

builds:
  - id: darwin-amd64
    binary: zname
    main: ./cmd/zname/main.go
    ldflags:
      - -s -w
      - -X zname/zname.version={{.Version}}
      - -X zname/zname.commit={{.Commit}}
      - -X zname/zname.date={{.Date}}
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/macos/amd64
      - PKG_CONFIG_PATH=/sysroot/macos/amd64/usr/local/lib/pkgconfig
      - CC=o64-clang
      - CXX=o64-clang++

  - id: linux-amd64
    binary: zname
    main: ./cmd/zname/main.go
    ldflags:
      - -s -w
      - -X zname.version={{.Version}}
      - -X zname.commit={{.Commit}}
      - -X zname.date={{.Date}}
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
      - CGO_FLAGS=--sysroot=/sysroot/linux/amd64
      - CGO_LDFLAGS=--sysroot=/sysroot/linux/amd64
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/linux/amd64
      - PKG_CONFIG_PATH=/sysroot/linux/amd64/opt/vc/lib/pkgconfig:/sysroot/linux/amd64/usr/lib/arm-linux-gnueabihf/pkgconfig:/sysroot/linux/amd64/usr/lib/pkgconfig:/sysroot/linux/amd64/usr/local/lib/pkgconfig


archives:
  - id: archive
    builds:
      - linux-amd64
      - darwin-amd64
    replacements:
      darwin: macOS
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    # Don't include any additional files into the archives (such as README, CHANGELOG etc).
    files:
      - none*

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: grdl
    name: zname

brews:
  - name: zname
    tap:
      owner: grdl
      name: homebrew-tap
    commit_author:
      name: Greg Dlugoszewski
      email: greg@grdl.dev
    folder: Formula
    homepage: https://github.com/grdl/zname/
    description: "Zname: search through your cloud DNS records."
    test: |
      system "zname --version"
    install: |
      bin.install "zname"
