before:
  hooks:
    - go mod tidy

builds:
  - id: darwin-amd64
    main: ./cmd/zname/main.go
#    binary: golang-cross
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/macos/amd64
      - PKG_CONFIG_PATH=/sysroot/macos/amd64/usr/local/lib/pkgconfig
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -mod=readonly


#  - id: linux-armhf
#    main: ./
#    binary: golang-cross
#    goos:
#      - linux
#    goarch:
#      - arm
#    goarm:
#      - 7
#    env:
#      - CC=arm-linux-gnueabihf-gcc
#      - CXX=arm-linux-gnueabihf-g++
#      - CGO_FLAGS=--sysroot=/sysroot/linux/armhf
#      - CGO_LDFLAGS=--sysroot=/sysroot/linux/armhf
#      - PKG_CONFIG_SYSROOT_DIR=/sysroot/linux/armhf
#      - PKG_CONFIG_PATH=/sysroot/linux/armhf/opt/vc/lib/pkgconfig:/sysroot/linux/armhf/usr/lib/arm-linux-gnueabihf/pkgconfig:/sysroot/linux/armhf/usr/lib/pkgconfig:/sysroot/linux/armhf/usr/local/lib/pkgconfig
#    flags:
#      - -mod=readonly
#    ldflags:
#      - -s -w -X main.version={{.Version}}

#builds:
#  - id: zname
#    main: ./cmd/zname/main.go
#    ldflags:
#      - -s -w
#      - -X zname.version={{.Version}}
#      - -X zname.commit={{.Commit}}
#      - -X zname.date={{.Date}}
#    env:
#      - CGO_ENABLED=1
#    goos:
#      - linux
#      - darwin
#      - windows

#archives:
#  - id: archive
#    builds:
#      - zname
#    replacements:
#      darwin: macOS
#      linux: linux
#      windows: windows
#      386: i386
#      amd64: x86_64
#    format_overrides:
#      - goos: windows
#        format: zip
#    # Don't include any additional files into the archives (such as README, CHANGELOG etc).
#    files:
#      - none*

#checksum:
#  name_template: 'checksums.txt'

#release:
#  github:
#    owner: grdl
#    name: zname

#brews:
#  - name: zname
#    tap:
#      owner: grdl
#      name: homebrew-tap
#    commit_author:
#      name: Greg Dlugoszewski
#      email: greg@grdl.dev
#    folder: Formula
#    homepage: https://github.com/grdl/zname/
#    description: "Zname: search through your cloud DNS records."
#    test: |
#      system "zname --version"
#    install: |
#      bin.install "zname"
