name: release

on:
  push:
    branches:
      - "cgo_testing"
    tags:
      - "**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
#      - run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v2
      - name: Clone Sysroot for OSXCross CGO Support
        run: |-
          git clone https://github.com/troian/golang-cross-example-sysroot.git sysroot
#      - name: Setup release environment
#        run: |-
#          echo 'GITHUB_TOKEN=${{secrets.GORELEASER_TOKEN}}' > .release-env
      - name: Run GoReleaser
        run: |-
          docker run \
          	--rm \
          	--privileged \
          	-e CGO_ENABLED=1 \
            -e GITHUB_TOKEN=${{secrets.GORELEASER_TOKEN}} \
          	-v /var/run/docker.sock:/var/run/docker.sock \
          	-v `pwd`:/go/src/github.com/grdl/zname \
          	-v `pwd`/sysroot:/sysroot \
          	-w /go/src/github.com/grdl/zname \
          	troian/golang-cross:v1.16.6 \
          	release --rm-dist