name: release

on:
  push:
    branches:
      - "cgo_testing"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - name: setup dependencies
        uses: actions/setup-go@v2
      - name: OSXCross for CGO Support
        run: |
          git clone https://github.com/troian/golang-cross-example-sysroot.git sysroot
      - name: Setup release environment
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GORELEASER_TOKEN}}' > .release-env
      - name: release publish
        run: |-
          docker run \
          	--rm \
          	--privileged \
          	-e CGO_ENABLED=1 \
          	--env-file .release-env \
          	-v /var/run/docker.sock:/var/run/docker.sock \
          	-v `pwd`:/go/src/github.com/grdl/zname \
          	-v `pwd`/sysroot:/sysroot \
          	-w /go/src/github.com/grdl/zname \
          	troian/golang-cross:v1.16.6 \
          	release --rm-dist